doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            enum: string
            set: string
        types:
            !php/const App\Doctrine\Dbal\Type\GroupTypeEnumType::NAME: App\Doctrine\Dbal\Type\GroupTypeEnumType
            !php/const App\Doctrine\Dbal\Type\SubscriberTypeEnumType::NAME: App\Doctrine\Dbal\Type\SubscriberTypeEnumType
            !php/const App\Doctrine\Dbal\Type\MaleClassificationEnumType::NAME: App\Doctrine\Dbal\Type\MaleClassificationEnumType
            !php/const App\Doctrine\Dbal\Type\SubscriberRoleEnumType::NAME: App\Doctrine\Dbal\Type\SubscriberRoleEnumType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
