framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    mailer:
        dsn: '%env(MAILER_DSN)%'
