nelmio_api_doc:
    documentation:
        info:
            title: TCA Api
            description: Telegram Analytics Channel/Chat
            version: 0.1.0
    areas:
        default:
            path_patterns:
                - ^/cabinet/api
