security:
    providers:
        admin_user_provider:
            memory:
                users:
                    '%env(resolve:ADMIN_USER_LOGIN)%':
                        password:   '%env(resolve:ADMIN_USER_PASSWORD_HASH)%'
                        roles:      ROLE_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:  bcrypt
            cost:       12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:    ^/admin
            anonymous:  false
            provider:   admin_user_provider
            http_basic: ~
            context:    'sonata_admin'

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
