version: '2'
services:
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www/
            - ./nginx/hosts:/etc/nginx/conf.d
            - ./logs:/var/log/nginx
        links:
            - php
    db:
        container_name: ${PROJECT_NAME}_db
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - ./db/data:/var/lib/mysql
        user: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        container_name: ${PROJECT_NAME}_php
        privileged: true
        build: ./php
        volumes:
            - ../:/var/www/
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
