parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $photoPublicDir: '%kernel.project_dir%/public/photo'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Dto,Enum,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\:
        resource: '../src/EventListener'
        tags:
            - { name: doctrine.event_subscriber }

    App\Service\TelegramAPIService:
        arguments:
            $proxyHost: '%env(string:MADELINEPROTO_CONNECTION_PROXY_HOST)%'
            $proxyPort: '%env(int:MADELINEPROTO_CONNECTION_PROXY_PORT)%'
            $proxyUsername: '%env(string:MADELINEPROTO_CONNECTION_PROXY_USERNAME)%'
            $proxyPassword: '%env(string:MADELINEPROTO_CONNECTION_PROXY_PASSWORD)%'
            $appId: '%env(string:MADELINEPROTO_CONNECTION_API_ID)%'
            $appHash: '%env(string:MADELINEPROTO_CONNECTION_API_HASH)%'
            $botToken: '%env(string:MADELINEPROTO_CONNECTION_BOT_TOKEN)%'

    App\Command\FetchGroupSubscriberCommand:
        bind:
            $defaultGroupId: '%env(string:DEFAULT_FETCH_GROUP_SUBSCRIBER)%'

    App\Command\FetchUserPhoto:
        bind:
            $mimeTypes: '@mime_types'
            $defaultGroupId: '%env(string:DEFAULT_FETCH_GROUP_SUBSCRIBER)%'

    App\Admin\GroupAdmin:
        public: true
        arguments:
            - ~
            - App\Entity\Group
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: Analytics, label: Group }

    App\Admin\SubscriberAdmin:
        public: true
        arguments:
            - ~
            - App\Entity\Subscriber
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: Analytics, label: Subscriber }
