parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $photoPublicDir: '%kernel.project_dir%/public/photo'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\TelegramAPIService:
        arguments:
            $proxyHost: '%env(string:MADELINEPROTO_CONNECTION_PROXY_HOST)%'
            $proxyPort: '%env(int:MADELINEPROTO_CONNECTION_PROXY_PORT)%'
            $proxyUsername: '%env(string:MADELINEPROTO_CONNECTION_PROXY_USERNAME)%'
            $proxyPassword: '%env(string:MADELINEPROTO_CONNECTION_PROXY_PASSWORD)%'
            $appId: '%env(string:MADELINEPROTO_CONNECTION_API_ID)%'
            $appHash: '%env(string:MADELINEPROTO_CONNECTION_API_HASH)%'
            $botToken: '%env(string:MADELINEPROTO_CONNECTION_BOT_TOKEN)%'

    App\Command\FetchGroupSubscriberCommand:
        bind:
            $defaultGroupId: '%env(string:DEFAULT_FETCH_GROUP_SUBSCRIBER)%'
